#!/bin/bash

# when I "archived" but forgot to remove from .gitmodules

set -eu

grep path .gitmodules | awk '{print $3;}' | while read -r d; do 
 if [ ! -e "$d" ]; then
    [ -e ".git/_archive_/$d" ] && echo "$d - archived" || echo "$d - gone"; 
    git config --file .gitmodules --remove-section "submodule.$d"
 fi
done
